language: node_js
node_js:
  - 12
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run qa
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
