language: node_js
node_js:
  - 5.4
before_install:
  - npm install -g grunt-cli
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < test/coverage/*/lcov.info
